- name: Demonstrate the debug module
  hosts: all
  become: true
  tasks:
     - name: Print interface
       debug:
           msg: "{{ansible_hostname}} -->familia : {{ansible_os_family}} tiene las interfaces: {{ ansible_interfaces }}"
