- name: Say Hello to our Favorite Looney Tune Characters
  hosts: all
  vars:
    looney_tunes_characters:
        bugs:
            full_name: Bugs A Bunny
        daffy:
            full_name: Daffy E Duck
        wiley:
            full_name: Wiley E Coyote
  tasks:
  - name: Show Our Favorite Looney Tunes
    debug:
       msg: "Hello there: {{ item.key }} your real name is {{ item.value.full_name }}"
    with_dict: "{{ looney_tunes_characters }}"
