- hosts: all
  user: vagrant
  become: true
  tasks:
  - name: Install VIM via yum
    yum:
      name: vim-enhanced
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install VIM via apt
    apt: 
      name: ['vim']
      state: present
    when: ansible_os_family == "Debian"

  - name: Unexpected OS family
    debug:
      msg: "OS Family {{ ansible_os_family }} is not supported"
    when: ansible_os_family != "RedHat" and ansible_os_family != "Debian"
